export enum NotificationStatus {
  TRANSACCIONEXITOSA = 'TRANSACCIONEXITOSA',

  TRANSACCIONFALLIDA = 'TRANSACCIONFALLIDA',

  SOLICITUDAMIGO = 'SOLICITUDAMIGO',

  AVISOIMPORTANTE = 'AVISOIMPORTANTE',

  ACTUALIZACIONCUENTA = 'ACTUALIZACIONCUENTA',

  PROMOCIONESPECIAL = 'PROMOCIONESPECIAL',
}
